### ISSUE TITLE
Server rules

### ISSUE THREAD

**Issue by cookiemonster** [cookiemonster/divd.community#6]

**Comment by WinkoErades** [comment]
It might be useful to do some further research on this:
https://github.com/mastodon/mastodon-ansible
https://github.com/ceejbot/mastodon-ansible
https://codeberg.org/stvo/mastodon-ansible-nodocker
https://docs.joinmastodon.org/admin/install/
https://docs.joinmastodon.org/admin/backups/

**Comment by cookiemonster** [comment]
Due to security reasons we choose to use Slack (for  now).
