### ISSUE TITLE
Community management

### ISSUE THREAD

**Issue by WinkoErades** [cookiemonster/divd.community#9]
Communities need attention, starting with a warm welcome and guidance for newcomers. A base and home for its residents.

**Comment by WinkoErades** [comment]
As a community manager within our company intranet and government lounge, I offer my help with community management.

**Comment by WinkoErades** [comment]
Useful links:
https://docs.joinmastodon.org/user/moderating/
https://docs.joinmastodon.org/admin/moderation/

**Comment by cookiemonster** [comment]
We zijn op zoek naar een gedreven en enthousiaste community managers om ons team te versterken.
Als community manager speel je een sleutelrol in het opbouwen, onderhouden en laten groeien van onze diverse gemeenschap van security researchers, ontwikkelaars, en geïnteresseerde individuen en organisaties.

Je belangrijkste verantwoordelijkheden zijn:
 - Actief beheren van onze openbare Slack om betrokkenheid te vergroten en gemeenschapsinteracties te stimuleren.
 - Ontwikkelen van strategieën om de community te laten groeien en het stimuleren van deelname aan projecten en initiatieven.
 - Fungeren als het aanspreekpunt voor communityleden, hen ondersteunen, vragen beantwoorden en zorgen voor een positieve ervaring binnen de gemeenschap.
 - Samenwerken met interne teams om feedback van de community te verzamelen en deze in te zetten om de diensten en initiatieven van de stichtingen te verbeteren.

**Comment by cookiemonster** [comment]
We are going to add an **opportunities** section to the portal. It is already added as a Slack channel

**Comment by cookiemonster** [comment]
opportunities
